### ISSUE TITLE
basic set up 

### ISSUE THREAD

**Issue by MalaRuparel2023** [numq/golang-clean-architecture-imageboard-backend#1]
I am using this demo with kotlin and latest Jellyfish android version. also instaled 3 required plugins but there is an error. Can you help  with  basic set up?

**Comment by numq** [comment]
I made some changes and added docker-compose, everything should work. 
However, please note that this project is outdated and unmaintained, making it not the best basis for your project. I recommend you check out the microservice based gRPC projects:
- [ecommerce-backend](https://github.com/numq/ecommerce-backend) - if you are interested in TypeScript and Go
- [dddating-backend](https://github.com/numq/dddating-backend) - if you are interested in Rust

This is a simple and fast way to create the services you need from scratch.

If you have questions or have a problem with something else, please ask.
